apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valkey-centralized-exporter.fullname" . }}
  labels:
    {{- include "valkey-centralized-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "valkey-centralized-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "valkey-centralized-exporter.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
    spec:
      serviceAccountName: {{ include "valkey-centralized-exporter.serviceAccountName" . }}
      containers:
      - name: exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: REDIS_EXPORTER_WEB_LISTEN_ADDRESS
          value: ":{{ .Values.service.port }}"
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: "json"
        - name: REDIS_PASSWORD
          value: {{ .Values.valkey.password | quote }}
        - name: REDIS_ADDR
          value: ""
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}