name: Package and Push Helm Chart to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  helm-chart-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPO: gitinsky

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: Package Helm chart
        run: |
          helm package .

      - name: Log in to Docker Hub (Helm OCI)
        run: |
          echo $DOCKER_HUB_PASSWORD | helm registry login registry-1.docker.io \
            --username $DOCKER_HUB_USERNAME --password-stdin

      - name: Push Helm chart to Docker Hub
        run: |
          CHART_PACKAGE=$(ls *.tgz | head -n 1)
          helm push $CHART_PACKAGE oci://registry-1.docker.io/${DOCKER_HUB_REPO}
